# -*- coding: utf-8 -*-
"""Atividade dos códigos aula 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdkfcy-RLG9DBohq7iVmzyY5zM3l5qzp

# Atividade da aula 3

Lista de códigos que aprendi com o melhor professor de programação ! :D

#Operadores Lógicos
"""

dia = 'segunda'
horario = 'manhã'
chovendo = False

if horario == 'manhã' and chovendo  ==  False:
    print("O sol está lindo")

if dia == 'sábado'  or  dia ==  'domingo':
    print("É fim de semana")

else:
  print('Não é fim de semana!')

"""#Laços de Repetição"""

for numero in range(7):
    print(numero)

"""#Tamanho de Listas"""

nomes = ['Pedro', 'Sinval', 'Felipe', 'Zarcky']

tamanho = len(nomes)

for indice in range(tamanho):
  print("O nome do indice", indice, "é", nomes[indice])

"""#Repetições Dinâmicas"""

animais = ['Cachorro', 'Gato', 'Papagaio', 'Cavalo', 'Furão', 'Esquilo']

for animal in animais:
  print("Espécie", animal)

numeros = [3, 6, 9, 12, 15, 18]

for numero in numeros:
  print("O valor", numero, "é multiplo de 3!")

"""# Funções"""

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2

  return media

def verificar_aprovacao(media):

  if media >= 6:
    print('O aluno foi aprovado!')
  else:
    print('O aluno foi reprovado')

media_aluno = calcular_media(8, 6.5)

verificar_aprovacao(media_aluno)

nota1 = 6.5
nota2 = 8.5

def verificar_aprovacao():
    media = calcular_media([nota1, nota2])

    if media >= 6:
        print('O aluno passou! :D')
    else:
        print('O aluno tem que estudar mais! D:')


def calcular_media(notas):
    quantidade = len(notas)

    soma = 0
    for nota in notas:
        soma = soma + nota

    media = soma / quantidade

    return media


verificar_aprovacao()

Frutas = ['Maça', 'Pera', 'Uva', 'Manga', 'Jaca']
Doces = ['Chocolate', 'Brigadeiro', 'Beijinho', 'Doce de leite']
Comidas = ['Macarrao', 'Feijao', 'Arroz', 'Torta de frango']
Bebidas = ['Cerveja', 'Achocolatado', 'Leite', 'Refrigerante', 'Suco de Uva']

Categorias = ['Frutas', 'Doces', 'Comidas', 'Bebidas']
compras = ['Frutas', 'Doces', 'Comidas', 'Bebidas']

for indice, categoria in enumerate(Categorias):
    print('Você precisa comprar', len(compras[indice]), categoria+':')
    for compra in compras[indice]:
        print('-', compra)

# Zarcky, dei uma estudada nessa parte e acho que fiz certo mas, não deveria sair o nome de cada item das listas? (tipo o nome das 6 frutas, dos 5 doces...)

def validar_idade(idade):
    if idade < 18:
        print('\nDesculpe, você não tem idade para prosseguir,', nome)
        return False
    else:
        print('\nÓtimo, você tem idade para prosseguir!,', nome)
        return True

def escolher_carta():
    print("Digite uma das opções abaixo:")
    print("1 - Carro\n2 - Moto\n3 - Carro e Moto")

    return int(input())

def calcular_preco(escolha):
    valor_carro = 1600
    valor_moto = 1100

    if escolha == 1:
        return valor_carro
    elif escolha ==2:
        return valor_moto
    else:
        return valor_carro + valor_moto

def desconto(valor):
    return valor - (valor * 0.10)

nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))

if validar_idade(idade):
    escolha = escolher_carta()

    print('\nPerfeito! Vou calcular o valor :D')
    valor = calcular_preco(escolha)

    print('\n'+nome, 'o valor total é de', valor, 'reais')
    print('Mas, vou ver o que posso fazer só um momentinho! :D')
    valor = desconto(valor)

    print('\nCom desconto eu consigo pra você por', valor, 'reais.')

    print('ficou interessante para o Sr(a)?\n1 - Sim\n2 - Não')
    interesse = int(input())
    if interesse == 1:
      print('\nPerfeito! começaremos amanhã então! :D')
    else:
      print('\nÉ uma pena, mas tudo bem! \nMe avisa caso mude de ideia ta bem? :D')

